### ISSUE TITLE
It's not working...!

### ISSUE THREAD

**Issue by lucapada** [morrismukiri/joomjson#2]
Hi! I installed this repo in a folder under my joomla's project: "http://localhost/joomla/api".
If I type into my browser this link "http://localhost/joomla/api", I get this data: "{"Name":"JoomJSON","Version":"1.0.0","author":"@morrismukiri","ok":true}".
Instead, if I type "http://localhost/joomla/api/articles", I get the apache "404 Not found" error. 
Similiar happened for the others controllers like article, categories, category...
What should I do?
Thank you so much!

**Comment by morrismukiri** [comment]
Next time install it in a different folder
